sudo: required

language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

services:
  - docker

before_install:
  - git submodule update --init --recursive

install:
  - docker-compose up -d

script:
  - |
    docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | while read CODE ; do
      if [ "$CODE" == "1" ]; then
        echo "-1"
      fi
    done

after_script:
  - docker-compose down

before_deploy:
  # Remove the git submodule.
  - mv drupal drupal_tmp
  - git submodule deinit drupal
  - rm drupal_tmp/.git
  - mv .git/modules/drupal drupal_tmp/.git
  - rmdir drupal
  - mv drupal_tmp drupal
  - cd drupal
  # Change the working tree of the git repository.
  - sed -i 's#\.\./\.\./\.\./drupal#..#' .git/config
  # Checkout dev branch.
  - git config core.fileMode false
  - git config core.autocrlf false
  - git checkout 8.6.x
  # Install composer libraries.
  - composer install --no-interaction --dev

  # Get the tagged release.
  - RELEASE_DIR="docker-core-sprint"
  - RELEASE_FILE="/tmp/${RELEASE_DIR}-${TRAVIS_BRANCH}.zip"
  - mkdir -p "/tmp/${RELEASE_DIR}"
  - cd /tmp
  - cp -a ${TRAVIS_BUILD_DIR}/. "${RELEASE_DIR}/"
  # Copies the example .gitignore file into drupal project directory.
  - cp "${RELEASE_DIR}/example.gitignore" "${RELEASE_DIR}/drupal/.gitignore"
  # Saves images to tarball inside release directory.
  - cd "/tmp/${RELEASE_DIR}"
  - IMAGES="wodby/adminer:4.3-1.1.0 wodby/drupal-apache:2.4-1.0.2 briangilbert/cloud9-alpine:20180318 linuxserver/thelounge:94 mailhog/mailhog:v1.0.0 wodby/mariadb:10.2-3.0.2 mradcliffe2/docker-drupal-php:core-0.4 traefik:1.5.2"
  - docker image save ${IMAGES} -o "/tmp/${RELEASE_DIR}/images.tar"
  - ./scripts/travis_wait 30 xz --verbose "/tmp/${RELEASE_DIR}/images.tar"
  # Removes this repository's .git/ directory and .travis.yml only.
  - cd /tmp
  - rm -rf "${RELEASE_DIR}/.git" "${RELEASE_DIR}/scripts"
  - rm "${RELEASE_DIR}/.travis.yml"
  - zip -q -r "${RELEASE_FILE}" "${RELEASE_DIR}" || echo -e "Failed to create release build!"

deploy:
  provider: releases
  api_key:
    secure: "bn2qpZqR5kt67aOwDSoJaHCN1G9lJYOE8Dy4kzG41VJmQYAaf0oGdq8AP9IxgaTDotGjsYhwLir4S1BzAWqlDWB63ZKZm0X0K56RZPwpLHevRUOz8sjZxzKa4VW2X3guBvdajOIMg3JKaa2OlWCPlzZ22VoCH3Go/XLe8bgtoDmonev6dJxSg8rPgFuFH5j636mcwgFKPBZaeDArO5dVlsW4O5Z69fwl1oLet+VOnd8Qkog2Tlle93jbF1EoQSsvjGKmPqkoscxyYNpqXLqVqQ+T/c0eN3OGieFUH2+7wDHqNszVWAdwoek0BRihrFmi+ycB5mmpx5YVjuyS6fzqCPVq9BlONjhxdJN0JBaUgSjkdrFKCwCK4zDT0WDCJEqMkp75A3FPS67EugiTbHqBjEujgtqR1Xy3JHr+w5ZUuTu5bYEMb8yidy27MZBJn6FY2wAZN1+8p/jYSjhSMYTtGGnhB3VeBUSnybZQ03+3ht+ngomzLut/hyNvy6ki4i/0W8Quan3e0F3mNsdkbsw3yGh+OpPXi8spW15EL/eK/Dd/H0EezRePaJ61w+GpTEQ+I991eKNmfiRwQttb96XeIqUhFGc2xwlOQqyDcNgTYg3moxTjUxRzPCkixQpMecCREt5s2XOzK8nuqxAVCK8W+ZHd+RR6l0+y/xLGFOzOEkg="
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true

